import type { Metadata } from "next";
import React from "react";

import { AuthProvider } from "../auth/AuthContext";

export const metadata: Metadata = {
    title: "Airbnb Authorizations",
    description: "Generated by create next app",
};

export default function AuthRootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return <AuthProvider>{children}</AuthProvider>;
}
